# This is a basic workflow to help you get started with Actions

name: Build Web App


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      id-token: write
      pages: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
  
      - name: Setup Nuget.exe for use with actions
        uses: Nuget/Setup-nuget@v1.0.2
        
      - name: Restore Nuget Packages
        run: nuget restore solution.sln
    
      - name: Build Solution
        run: msbuild solution.sln
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Bundle
          path: "./_build"
